"""siudma migracja

Revision ID: 32eabd3ecaf5
Revises: a6a20f0661ee
Create Date: 2025-08-07 13:58:04.509887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32eabd3ecaf5'
down_revision = 'a6a20f0661ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), server_default='123admin', nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=80), server_default='admin123', nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), server_default='Piotrek', nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), server_default='Palak', nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=80), server_default='dummy.email@gmail.com', nullable=False))
        batch_op.create_unique_constraint('uq_user_email', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
