"""czwarta migracja

Revision ID: 643776ea9d22
Revises: ce80f8f17a75
Create Date: 2025-08-07 13:34:25.151950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643776ea9d22'
down_revision = 'ce80f8f17a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('first_name')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
