"""piata migracja

Revision ID: 987b6299a7db
Revises: 643776ea9d22
Create Date: 2025-08-07 13:38:47.383799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987b6299a7db'
down_revision = '643776ea9d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=80), server_default='admin123', nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), server_default='Piotrek', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('first_name')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
