"""szosta migracja

Revision ID: a6a20f0661ee
Revises: 987b6299a7db
Create Date: 2025-08-07 13:49:58.279786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a20f0661ee'
down_revision = '987b6299a7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')
        batch_op.drop_column('last_name')
        batch_op.drop_column('email')
        batch_op.drop_column('first_name')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), server_default=sa.text("'admin123'"), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=80), server_default=sa.text("'Piotrek'"), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=80), server_default=sa.text("'dummy.email@gmail.com'"), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
