imie = input("Podaj imie jubilata: ")
nazwisko = input("Podaj nazwisko jubilata: ")
imie_i_nazwisko_nadawcy = input("podaj imie i nazwisko nadawcy: ")
zyczenia = input("Wpisz swoje zyczenia: ")
wiek = input("Podaj date urodzenia: ")
print(imie, nazwisko)
print(f"Wszystkiego najlepszego z okazji {2025 - int(wiek)} urodzin")
print(zyczenia)
print(imie_i_nazwisko_nadawcy)